import 'package:spikeai/widgets/app_bar/custom_app_bar.dart';import 'package:spikeai/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:spikeai/widgets/app_bar/appbar_subtitle.dart';import 'package:spikeai/widgets/custom_icon_button.dart';import 'package:spikeai/widgets/custom_elevated_button.dart';import 'package:spikeai/widgets/custom_text_form_field.dart';import 'widgets/paymentmethodlist_item_widget.dart';import 'package:flutter/material.dart';import 'package:spikeai/core/app_export.dart';
// ignore_for_file: must_be_immutable
class ReviewFillScreen extends StatelessWidget {ReviewFillScreen({Key? key}) : super(key: key);

TextEditingController startDateEditTextController = TextEditingController();

TextEditingController endDateEditTextController = TextEditingController();

TextEditingController televisionEditTextController = TextEditingController();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 21.v), child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 17.v), Expanded(child: SingleChildScrollView(child: Padding(padding: EdgeInsets.only(bottom: 5.v), child: Column(children: [_buildEstatesCardTransaction(context), SizedBox(height: 37.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 24.h), child: Text("Period", style: theme.textTheme.titleMedium))), SizedBox(height: 16.v), _buildFormDateFill(context), SizedBox(height: 37.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 24.h), child: Text("Note for Owner", style: theme.textTheme.titleMedium))), SizedBox(height: 16.v), _buildTelevisionEditText(context), SizedBox(height: 39.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 24.h), child: Text("Payment Method", style: theme.textTheme.titleMedium))), SizedBox(height: 14.v), _buildPaymentMethodList(context), SizedBox(height: 36.v), _buildItemHeaderRow(context), SizedBox(height: 16.v), _buildCardCoupon(context), SizedBox(height: 50.v), CustomImageView(imagePath: ImageConstant.imageNotFound, height: 1.v, width: 100.h)]))))])), bottomNavigationBar: _buildNext(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 74.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 24.h, top: 3.v, bottom: 3.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitle(text: "Transaction review")); } 
/// Section Widget
Widget _buildApartmentButton(BuildContext context) { return CustomElevatedButton(height: 24.v, width: 72.h, text: "Apartment", leftIcon: Container(margin: EdgeInsets.only(right: 6.h), child: CustomImageView(imagePath: ImageConstant.imgClose, height: 13.v, width: 11.h)), buttonStyle: CustomButtonStyles.fillBlueGrayAfTL8, buttonTextStyle: CustomTextStyles.labelSmallGray100); } 
/// Section Widget
Widget _buildRentButton(BuildContext context) { return CustomElevatedButton(height: 50.v, width: 94.h, text: "Rent", leftIcon: Container(margin: EdgeInsets.only(right: 8.h), child: CustomImageView(imagePath: ImageConstant.imgClose, height: 18.v, width: 15.h)), buttonStyle: CustomButtonStyles.fillWhiteATL25, buttonTextStyle: theme.textTheme.labelMedium!, alignment: Alignment.centerRight); } 
/// Section Widget
Widget _buildEstatesCardTransaction(BuildContext context) { return Container(margin: EdgeInsets.symmetric(horizontal: 24.h), padding: EdgeInsets.all(8.h), decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder25), child: Row(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 140.v, width: 168.h, child: Stack(alignment: Alignment.centerLeft, children: [CustomImageView(imagePath: ImageConstant.imgShape20, height: 140.v, width: 168.h, radius: BorderRadius.circular(18.h), alignment: Alignment.center), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 8.h, right: 88.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomIconButton(height: 25.adaptSize, width: 25.adaptSize, padding: EdgeInsets.all(6.h), decoration: IconButtonStyleHelper.fillWhiteATL121, child: CustomImageView(imagePath: ImageConstant.imgFavoriteRedA200)), SizedBox(height: 75.v), _buildApartmentButton(context)])))])), Padding(padding: EdgeInsets.fromLTRB(16.h, 8.v, 9.h, 8.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(width: 88.h, child: Text("Sky Dandelions\nApartment", maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.labelLarge!.copyWith(height: 1.50))), SizedBox(height: 6.v), Row(children: [CustomImageView(imagePath: ImageConstant.imgLinkedin, height: 12.adaptSize, width: 12.adaptSize), Padding(padding: EdgeInsets.only(left: 4.h), child: Text("Jakarta, Indonesia", style: theme.textTheme.labelSmall))]), SizedBox(height: 18.v), _buildRentButton(context)]))])); } 
/// Section Widget
Widget _buildStartDateEditText(BuildContext context) { return CustomTextFormField(width: 163.h, controller: startDateEditTextController, hintText: "11/28/2021", hintStyle: CustomTextStyles.labelLargeSemiBold, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 25.v, 16.h, 25.v), child: CustomImageView(imagePath: ImageConstant.imgCalendar, height: 20.adaptSize, width: 20.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 70.v)); } 
/// Section Widget
Widget _buildEndDateEditText(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 6.h), child: CustomTextFormField(width: 160.h, controller: endDateEditTextController, hintText: "01/28/2022", hintStyle: CustomTextStyles.labelLargeSemiBold, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 25.v, 16.h, 25.v), child: CustomImageView(imagePath: ImageConstant.imgCalendar, height: 20.adaptSize, width: 20.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 70.v))); } 
/// Section Widget
Widget _buildFormDateFill(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 23.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [_buildStartDateEditText(context), _buildEndDateEditText(context)])); } 
/// Section Widget
Widget _buildTelevisionEditText(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: CustomTextFormField(controller: televisionEditTextController, hintText: "Please, clean before I go there", textInputAction: TextInputAction.done, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 25.v, 16.h, 25.v), child: CustomImageView(imagePath: ImageConstant.imgTelevision, height: 20.adaptSize, width: 20.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 70.v))); } 
/// Section Widget
Widget _buildPaymentMethodList(BuildContext context) { return Align(alignment: Alignment.centerRight, child: SizedBox(height: 180.v, child: ListView.separated(padding: EdgeInsets.only(left: 24.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 10.h);}, itemCount: 3, itemBuilder: (context, index) {return PaymentmethodlistItemWidget();}))); } 
/// Section Widget
Widget _buildItemHeaderRow(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("Have a voucher?", style: theme.textTheme.titleMedium), Padding(padding: EdgeInsets.only(top: 4.v, bottom: 2.v), child: Text("change voucher", style: CustomTextStyles.labelLargePrimary))])); } 
/// Section Widget
Widget _buildHlwn40Button(BuildContext context) { return CustomElevatedButton(height: 52.v, width: 128.h, text: "HLWN40", margin: EdgeInsets.only(bottom: 1.v), buttonStyle: CustomButtonStyles.fillGreenATL17, buttonTextStyle: CustomTextStyles.titleMediumMontserratWhiteA700Bold); } 
/// Section Widget
Widget _buildCardCoupon(BuildContext context) { return Container(margin: EdgeInsets.symmetric(horizontal: 24.h), padding: EdgeInsets.all(16.h), decoration: AppDecoration.gradientGreenAToTealA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder25), child: Row(mainAxisSize: MainAxisSize.max, children: [_buildHlwn40Button(context), Padding(padding: EdgeInsets.only(left: 10.h, top: 10.v, bottom: 10.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Halloween sale", style: theme.textTheme.labelLarge), SizedBox(height: 7.v), Text("Get 40% off on all transactions", style: theme.textTheme.labelSmall)]))])); } 
/// Section Widget
Widget _buildNext(BuildContext context) { return CustomElevatedButton(text: "Next", margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 24.v), onPressed: () {onTapNext(context);}); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
/// Navigates to the summaryScreen when the action is triggered.
onTapNext(BuildContext context) { Navigator.pushNamed(context, AppRoutes.summaryScreen); } 
 }
