import 'package:spikeai/widgets/app_bar/custom_app_bar.dart';import 'package:spikeai/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:spikeai/widgets/custom_pin_code_text_field.dart';import 'package:spikeai/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:spikeai/core/app_export.dart';class FormOtpScreen extends StatelessWidget {const FormOtpScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 21.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 28.v), SizedBox(width: 219.h, child: Text("Enter the \nverification code 🔒 ", maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.headlineSmall!.copyWith(height: 1.50))), SizedBox(height: 26.v), Container(width: 272.h, margin: EdgeInsets.only(right: 54.h), child: RichText(text: TextSpan(children: [TextSpan(text: "Enter thpe 4 digit code that we just sent to \n", style: CustomTextStyles.bodyMediumff53577a), TextSpan(text: "user@email.com", style: CustomTextStyles.bodyMediumff242b5c)]), textAlign: TextAlign.left)), SizedBox(height: 46.v), CustomPinCodeTextField(context: context, onChanged: (value) {}), Spacer(), CustomElevatedButton(height: 50.v, width: 87.h, text: "00.21", leftIcon: Container(margin: EdgeInsets.only(right: 8.h), child: CustomImageView(imagePath: ImageConstant.imgClock, height: 20.adaptSize, width: 20.adaptSize)), buttonStyle: CustomButtonStyles.fillGrayTL25, buttonTextStyle: CustomTextStyles.bodySmallBluegray80001_1, alignment: Alignment.center), SizedBox(height: 21.v), Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 41.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("Didn’t receive the OTP?", style: theme.textTheme.bodyMedium), Padding(padding: EdgeInsets.only(left: 12.h), child: Text("Resend OTP", style: CustomTextStyles.titleSmallPrimaryBold))])))])), bottomNavigationBar: _buildSubmitButton(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: double.maxFinite, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.fromLTRB(24.h, 3.v, 301.h, 3.v), onTap: () {onTapArrowLeft(context);})); } 
/// Section Widget
Widget _buildSubmitButton(BuildContext context) { return CustomElevatedButton(text: "Submit", margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 24.v), onPressed: () {onTapSubmitButton(context);}); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
/// Navigates to the locationEmptyScreen when the action is triggered.
onTapSubmitButton(BuildContext context) { Navigator.pushNamed(context, AppRoutes.locationEmptyScreen); } 
 }
